services:
  ml-app:
    build: .
    container_name: ml_project_app
    ports:
      - "5000:5000"  # Открываем порт 5000
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./plots:/app/plots
    environment:
      - PYTHONPATH=/app